### ISSUE TITLE
ERROR TypeError: value.trim is not a function

### ISSUE THREAD

**Issue by NeoSimvolist** [KingMario/packages#8] opened 2019-10-14 16:40 UTC
an error is issued here if the field type is number

https://github.com/KingMario/packages/blob/5b3dd84eb1b1adb2d510eb1b65a6604eb74239f3/projects/ngx-trim-directive/src/lib/ngx-trim.directive.ts#L103

At least make the shutdown work like this <input [trim] = "false">. This does not help at the moment.

**Comment by KingMario** [comment] 2019-10-14 22:37
Hi @NeoSimvolist 

Thanks for the bug report.

But I'm curious that, why will you trim a number?

Could you please give me the use case before I make the update?

Thanks.

**Comment by KingMario** [comment] 2019-10-15 05:24
Hi @NeoSimvolist 

The issue is addressed in 77629f9. Please verify it with the new version 1.0.9.

Thanks.

**Closed as completed by KingMario** 2019-10-15 05:24 UTC

**Comment by KingMario** [comment] 2019-10-17 02:11
Hi @NeoSimvolist

Please use v 1.0.10 with one more bug-fix.

Thanks.
